/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.DangNhapGUI;
import Entities.SVCQ;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import BLL.SVCQBLL;
import DAL.ConnectSQL;
import DAL.SVCQDAL;
import DAL.SVCQDAL;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Than
 */
public class SVCQGUI extends javax.swing.JFrame {

    private ArrayList<SVCQ> list;

    DefaultTableModel model;

    /**
     * Creates new form StudentView
     */
    public SVCQGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        list = new SVCQDAL().show();
        model = (DefaultTableModel) jTable1.getModel();
        showResult(list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelMSSV = new javax.swing.JLabel();
        jLabelTenSV = new javax.swing.JLabel();
        jLabelNienKhoa = new javax.swing.JLabel();
        txtMSSV = new javax.swing.JTextField();
        txtTenSV = new javax.swing.JTextField();
        txtNienKhoa = new javax.swing.JTextField();
        jButtonTHEM = new javax.swing.JButton();
        jButtonXOA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonSVTC = new javax.swing.JButton();
        jButtonSUA = new javax.swing.JButton();
        jButtonDSTotnghiep = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelSDT = new javax.swing.JLabel();
        jLabelVATLI = new javax.swing.JLabel();
        jLabelGIAITICH = new javax.swing.JLabel();
        jLabelDAISO = new javax.swing.JLabel();
        jLabelCSDL = new javax.swing.JLabel();
        jLabelOOP = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldSDT = new javax.swing.JTextField();
        jTextFieldVATLI = new javax.swing.JTextField();
        jTextFieldGIAITICH = new javax.swing.JTextField();
        jTextFieldDAISO = new javax.swing.JTextField();
        jTextFieldCSDL = new javax.swing.JTextField();
        jTextFieldOOP = new javax.swing.JTextField();
        jTextFieldHDH = new javax.swing.JTextField();
        jTextFieldPRJ1 = new javax.swing.JTextField();
        jTextFieldPRJ2 = new javax.swing.JTextField();
        jTextFieldPRJ3 = new javax.swing.JTextField();
        jTextFieldDOAN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TT Sinh Viên");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("THÔNG TIN SINH VIÊN");

        jLabelMSSV.setText("MSSV :");

        jLabelTenSV.setText("Tên Sinh Viên : ");

        jLabelNienKhoa.setText("Khóa :");

        jButtonTHEM.setText("Thêm SV");
        jButtonTHEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTHEMActionPerformed(evt);
            }
        });

        jButtonXOA.setText("Xóa SV");
        jButtonXOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXOAActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "MSSV", "Tên SV", "Khóa", "SDT", "Vật Lý", "Giải Tích", "Đại Số", "CSDL", "OOP", "HDH", "Project 1", "Project 2", "Project 3", "Đồ Án", "Điểm TB", "Tốt Nghiệp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
            jTable1.getColumnModel().getColumn(9).setResizable(false);
            jTable1.getColumnModel().getColumn(10).setResizable(false);
            jTable1.getColumnModel().getColumn(11).setResizable(false);
            jTable1.getColumnModel().getColumn(12).setResizable(false);
            jTable1.getColumnModel().getColumn(13).setResizable(false);
            jTable1.getColumnModel().getColumn(14).setResizable(false);
            jTable1.getColumnModel().getColumn(15).setResizable(false);
            jTable1.getColumnModel().getColumn(16).setResizable(false);
            jTable1.getColumnModel().getColumn(16).setPreferredWidth(90);
        }

        jButtonSVTC.setText("Sinh Viên Tín Chỉ");
        jButtonSVTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSVTCActionPerformed(evt);
            }
        });

        jButtonSUA.setText("Sửa SV");
        jButtonSUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSUAActionPerformed(evt);
            }
        });

        jButtonDSTotnghiep.setText("Danh Sách Tốt Nghiệp");
        jButtonDSTotnghiep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDSTotnghiepActionPerformed(evt);
            }
        });

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButton1.setText("Đăng Xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelSDT.setText("SĐT :");

        jLabelVATLI.setText("Vật Lý :");

        jLabelGIAITICH.setText("Giải Tích :");

        jLabelDAISO.setText("Đại Số :");

        jLabelCSDL.setText("Cơ Sở Dữ Liệu :");

        jLabelOOP.setText("OOP :");

        jLabel2.setText("Hệ Điều Hành :");

        jLabel3.setText("Project 1 :");

        jLabel4.setText("Project 2 :");

        jLabel5.setText("Project 3 :");

        jLabel6.setText("Đồ Án :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Quản Lý Chung : Đỗ Thị Ngọc Diệp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldPRJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldPRJ3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldDOAN, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTenSV)
                                    .addComponent(jLabelMSSV)
                                    .addComponent(jLabelNienKhoa)
                                    .addComponent(jLabelSDT)
                                    .addComponent(jLabelGIAITICH)
                                    .addComponent(jLabelVATLI)
                                    .addComponent(jLabelDAISO)
                                    .addComponent(jLabelOOP)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabelCSDL))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldPRJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldCSDL, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtNienKhoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                                .addComponent(txtTenSV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                                .addComponent(txtMSSV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                                .addComponent(jTextFieldSDT, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldVATLI, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldGIAITICH, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldDAISO, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(jTextFieldOOP, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldHDH, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonTHEM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSUA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonXOA, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonDSTotnghiep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSVTC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 728, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(742, 742, 742))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMSSV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTenSV)
                            .addComponent(txtTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNienKhoa)
                            .addComponent(txtNienKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSDT)
                            .addComponent(jTextFieldSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelVATLI)
                            .addComponent(jTextFieldVATLI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGIAITICH)
                            .addComponent(jTextFieldGIAITICH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDAISO)
                            .addComponent(jTextFieldDAISO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldCSDL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCSDL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldOOP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelOOP))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldHDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPRJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPRJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPRJ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDOAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonTHEM)
                            .addComponent(jButtonSUA)
                            .addComponent(jButtonXOA)
                            .addComponent(jButtonReset))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButtonSVTC)
                            .addComponent(jButtonDSTotnghiep))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public void showSVCQ() {
        jTable1.setModel(model); // load data to table
//        model.setHorizontalAlignment( JLabel.CENTER );// Căn giữa dữ liệu bảng
//        tbKhu.setDefaultRenderer(Object.class, renderer);// chỉ căn giữa dữ liệu là String

//        cbbMaKhu.setModel(KhuCanHoBLL.cbb_show()); //load data to combobox
    }
    private void jButtonXOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXOAActionPerformed
        // TODO add your handling code here:

        clearData(list);
        int i = jTable1.getSelectedRow();

        new SVCQDAL().delete((String) jTable1.getValueAt(i, 1));
        list = new SVCQDAL().show();
        model.setRowCount(0);
        jTable1.setModel(model);
        showResult(list);
        reset();

    }//GEN-LAST:event_jButtonXOAActionPerformed

    public void reset() {
        txtMSSV.setText("");
        txtNienKhoa.setText("");
        txtTenSV.setText("");
        jTextFieldCSDL.setText("");
        jTextFieldDAISO.setText("");
        jTextFieldDOAN.setText("");
        jTextFieldGIAITICH.setText("");
        jTextFieldHDH.setText("");
        jTextFieldOOP.setText("");
        jTextFieldPRJ1.setText("");
        jTextFieldPRJ2.setText("");
        jTextFieldPRJ3.setText("");
        jTextFieldSDT.setText("");
        jTextFieldVATLI.setText("");
    }
    private void jButtonTHEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTHEMActionPerformed
        clearData(list);
        SVCQ svcq = new SVCQ();
        svcq.setMSSV(txtMSSV.getText());
        svcq.setTenSV(txtTenSV.getText());
        svcq.setNienKhoa(Integer.parseInt(txtNienKhoa.getText()));
        svcq.setSDT(jTextFieldSDT.getText());
        svcq.setVatLi(Float.parseFloat(jTextFieldVATLI.getText()));
        svcq.setGiaiTich(Float.parseFloat(jTextFieldGIAITICH.getText()));
        svcq.setDaiSo(Float.parseFloat(jTextFieldDAISO.getText()));
        svcq.setCSDL(Float.parseFloat(jTextFieldCSDL.getText()));
        svcq.setOOP(Float.parseFloat(jTextFieldOOP.getText()));
        svcq.setHDH(Float.parseFloat(jTextFieldHDH.getText()));
        svcq.setProject1(Float.parseFloat(jTextFieldPRJ1.getText()));
        svcq.setProject2(Float.parseFloat(jTextFieldPRJ2.getText()));
        svcq.setProject3(Float.parseFloat(jTextFieldPRJ3.getText()));
        svcq.setDoAn(Float.parseFloat(jTextFieldDOAN.getText()));
        svcq.setDiemTB(svcq.getDiemTB());
        svcq.setTotNghiep(svcq.isTotNghiep());

        new SVCQDAL().insert(svcq);
        list = new SVCQDAL().show();

        model.setRowCount(0);
        jTable1.setModel(model);
        showResult(list);
        reset();


    }//GEN-LAST:event_jButtonTHEMActionPerformed

    private void jButtonSUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSUAActionPerformed
        // TODO add your handling code here:

        clearData(list);
        int i = jTable1.getSelectedRow();

        clearData(list);
        SVCQ svcq = new SVCQ();
        svcq.setMSSV(txtMSSV.getText());
        svcq.setTenSV(txtTenSV.getText());
        svcq.setNienKhoa(Integer.parseInt(txtNienKhoa.getText()));
        svcq.setSDT(jTextFieldSDT.getText());
        svcq.setVatLi(Float.parseFloat(jTextFieldVATLI.getText()));
        svcq.setGiaiTich(Float.parseFloat(jTextFieldGIAITICH.getText()));
        svcq.setDaiSo(Float.parseFloat(jTextFieldDAISO.getText()));
        svcq.setCSDL(Float.parseFloat(jTextFieldCSDL.getText()));
        svcq.setOOP(Float.parseFloat(jTextFieldOOP.getText()));
        svcq.setHDH(Float.parseFloat(jTextFieldHDH.getText()));
        svcq.setProject1(Float.parseFloat(jTextFieldPRJ1.getText()));
        svcq.setProject2(Float.parseFloat(jTextFieldPRJ2.getText()));
        svcq.setProject3(Float.parseFloat(jTextFieldPRJ3.getText()));
        svcq.setDoAn(Float.parseFloat(jTextFieldDOAN.getText()));
        svcq.setDiemTB(svcq.getDiemTB());
        svcq.setTotNghiep(svcq.isTotNghiep());
        new SVCQDAL().update(svcq.getMSSV(), svcq.getTenSV(), svcq.getNienKhoa(), svcq.getSDT(), svcq.getVatLi(), svcq.getDaiSo(), svcq.getGiaiTich(), svcq.getCSDL(), svcq.getOOP(), svcq.getHDH(), svcq.getProject1(), svcq.getProject2(), svcq.getProject3(), svcq.getDoAn());
        list = new SVCQDAL().show();
        model.setRowCount(0);
        jTable1.setModel(model);
        showResult(list);
        reset();

    }//GEN-LAST:event_jButtonSUAActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        txtMSSV.setText((String) jTable1.getValueAt(i, 1));
        txtTenSV.setText((String) jTable1.getValueAt(i, 2));
        txtNienKhoa.setText((String) jTable1.getValueAt(i, 3).toString());
        jTextFieldSDT.setText((String) jTable1.getValueAt(i, 4).toString());
        jTextFieldVATLI.setText((String) jTable1.getValueAt(i, 5).toString());
        jTextFieldGIAITICH.setText((String) jTable1.getValueAt(i, 6).toString());
        jTextFieldDAISO.setText((String) jTable1.getValueAt(i, 7).toString());
        jTextFieldCSDL.setText((String) jTable1.getValueAt(i, 8).toString());
        jTextFieldOOP.setText((String) jTable1.getValueAt(i, 9).toString());
        jTextFieldHDH.setText((String) jTable1.getValueAt(i, 10).toString());
        jTextFieldPRJ1.setText((String) jTable1.getValueAt(i, 11).toString());
        jTextFieldPRJ2.setText((String) jTable1.getValueAt(i, 12).toString());
        jTextFieldPRJ3.setText((String) jTable1.getValueAt(i, 13).toString());
        jTextFieldDOAN.setText((String) jTable1.getValueAt(i, 14).toString());


    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonDSTotnghiepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDSTotnghiepActionPerformed
        // TODO add your handling code here:        
        this.dispose();
        SVCQTN s = new SVCQTN();
        s.setVisible(true);

    }//GEN-LAST:event_jButtonDSTotnghiepActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DangNhapGUI s = new DangNhapGUI();
        s.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSVTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSVTCActionPerformed
        // TODO add your handling code here:
        this.dispose();
        SVTCGUI s = new SVTCGUI();
        s.setVisible(true);
    }//GEN-LAST:event_jButtonSVTCActionPerformed

    public void showResult(ArrayList<SVCQ> list) {
//        SVCQ s = getList().get(getList().size() - 1);
//         model.addRow(new Object[]{
//            i++, s.getMSSV(), s.getTenSV(), s.getNienKhoa(), s.getSDT(), s.getTCHT(), s.getTCCL(), s.getDiemTB(), s.isTotNghiep()
//        });  
        int i = 1;
        for (SVCQ s : list) {
            model.addRow(new Object[]{
                i++, s.getMSSV(), s.getTenSV(), s.getNienKhoa(), s.getSDT(), s.getVatLi(), s.getGiaiTich(), s.getDaiSo(), s.getCSDL(), s.getOOP(), s.getHDH(), s.getProject1(), s.getProject2(), s.getProject3(), s.getDoAn(), s.getDiemTB(), s.isTotNghiep()
            });
        }

    }

    public void clearData(ArrayList<SVCQ> list) {
        System.out.println("size1 = " + list.size());
        list.clear();
        System.out.println("size = " + list.size());
//            (int i = 0;i<list.size();i++){
//                jTable1.removeAll;
//            }
//            jTable1.setModel(model);

    }

    public void clearTable() {
        jTable1.setModel(new DefaultTableModel(null, new String[]{}));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SVCQGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SVCQGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SVCQGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SVCQGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SVCQGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDSTotnghiep;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSUA;
    private javax.swing.JButton jButtonSVTC;
    private javax.swing.JButton jButtonTHEM;
    private javax.swing.JButton jButtonXOA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCSDL;
    private javax.swing.JLabel jLabelDAISO;
    private javax.swing.JLabel jLabelGIAITICH;
    private javax.swing.JLabel jLabelMSSV;
    private javax.swing.JLabel jLabelNienKhoa;
    private javax.swing.JLabel jLabelOOP;
    private javax.swing.JLabel jLabelSDT;
    private javax.swing.JLabel jLabelTenSV;
    private javax.swing.JLabel jLabelVATLI;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCSDL;
    private javax.swing.JTextField jTextFieldDAISO;
    private javax.swing.JTextField jTextFieldDOAN;
    private javax.swing.JTextField jTextFieldGIAITICH;
    private javax.swing.JTextField jTextFieldHDH;
    private javax.swing.JTextField jTextFieldOOP;
    private javax.swing.JTextField jTextFieldPRJ1;
    private javax.swing.JTextField jTextFieldPRJ2;
    private javax.swing.JTextField jTextFieldPRJ3;
    private javax.swing.JTextField jTextFieldSDT;
    private javax.swing.JTextField jTextFieldVATLI;
    private javax.swing.JTextField txtMSSV;
    private javax.swing.JTextField txtNienKhoa;
    private javax.swing.JTextField txtTenSV;
    // End of variables declaration//GEN-END:variables
}
